name: CI
on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '30 13 * * 5'
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - id: time
        run: |
          time=nightly-$(date +'%Y/%m/%d')
          echo "::set-output name=time::$time"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: brew install make ninja
      - run: make clean
      - run: make tools
      - run: make
      - name: Package tar.xz archive
        run: tar -cf - PathOfBuilding.app | xz -c > PathOfBuilding.darwin.tar.xz
      - name: Checking GUI 
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }} 
        run: |
            ./PathOfBuilding.app/Contents/MacOS/pobWrapper.sh &
            sleep 10
            screencapture /tmp/sl.png
            export IMG_URL=`curl -L -X POST https://api.imgur.com/3/image -H "Authorization: Client-ID ${IMGUR_CLIENT_ID}" -F image=@/tmp/sl.png | jq '.data | .link' | tr -d '"'`
            pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
            curl -X POST -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${GIT_TOKEN}" \
              https://api.github.com/repos/aspel/pobfrontend/issues/${pull_number}/comments \
              -d "{\"body\":\"![Screenshot MacOS](${IMG_URL})\n${GITHUB_SHA} : MacOS\"}"
            echo $IMG_URL
        if: github.ref != 'refs/heads/master'
      - run: tar -tvf PathOfBuilding.darwin.tar.xz
      - name: Upload MacOS artifacts into Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "PathOfBuilding.darwin.tar.xz"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: PathOfBuilding
          body: "${{steps.time.outputs.time}}"
        if: github.ref == 'refs/heads/master'
  